### ISSUE TITLE
[Bug]: Browser hang on My Account Page

### ISSUE THREAD

**Issue by ashishkpaul** [vuestorefront-community/vendure#234] opened 2022-08-02 13:04 UTC
### Expected Behavior

it should shown user profile

### Actual Behavior

Browser stuck while clicking on https://example.com/my-account and not showing any pm2 log error

### Steps to reproduce

1. Create An Account
2. Sign In
3. click on my-account button (user icon)

### What version of vendure integration are you using?

1.6.4

### What version of Node.js are you using?

v14.19.3

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

Linux

### Relevant log output

```shell
not showing any log
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashishkpaul** [comment] 2022-08-05 07:04
I deployed vendure-1.6.4 ecommerce and storefront again on local host and configured as written in a guide https://docs.vuestorefront.io/vendure/guide/configuration.html#requirements and getting an error
[dev:*theme]  ERROR  [VSF][error]:  [GraphQL error]: Message: You are not currently authorized to perform this action, Location: [column: 3, line: 2], Path: me

**Comment by Baroshem** [comment] 2022-08-05 07:59
Hey @ashishkpaul 

Sorry for no contact, I completely missed your issue.

Can you check if you have a cookie stored in your browser after logging in?

**Comment by ashishkpaul** [comment] 2022-08-05 08:26
yes sir its storing 

![Screenshot_2022-08-05_13-55-42](https://user-images.githubusercontent.com/16308863/183035842-ab53ff17-b618-4881-8441-65e39a0cc8a3.png)

**Comment by ashishkpaul** [comment] 2022-08-05 08:30
when i refresh the page after login my-account page not showing user data 
![Screenshot_2022-08-05_13-59-55](https://user-images.githubusercontent.com/16308863/183036553-94f779f7-a594-4eaf-ba3b-6eb53a0baeaf.png)

**Comment by Baroshem** [comment] 2022-08-05 08:58
@ashishkpaul 

Please check in the dev tools if the`vendure-auth-token` cookie is correctly set after login?

**Comment by ashishkpaul** [comment] 2022-08-05 09:19
Hello sir, I am not a developer,  Vendure authOptions is

`   authOptions: {
        superadminCredentials: {
            identifier: 'superadmin',
            password: 'superadmin',
        },
        cookieOptions: {
          secret: process.env.COOKIE_SECRET || 'cookie-secret',
        },
    tokenMethod: 'bearer', // authorization header method
    requireVerification: false, // disable register by email verification
    },`

**Comment by Baroshem** [comment] 2022-08-05 09:29
In the browser, not in the configuration 
![image](https://user-images.githubusercontent.com/37120330/183048150-0503369e-617a-49e6-bfcf-4b46f11c4459.png)

**Comment by ashishkpaul** [comment] 2022-08-05 09:43
Sorry for delay sir, deployment was was stuck on localhost. I am sending the snapshop of public server https://vsf.dingpack.com/
![Screenshot_2022-08-05_15-10-22](https://user-images.githubusercontent.com/16308863/183050856-25f234ac-e874-41f9-bb5b-731e5ad16ac2.png)

**Comment by Baroshem** [comment] 2022-08-05 10:14
I cant really help with that. It seems that for some reason in your case, the redirect to my-account is not working even when a user is signed in. 

Could you do some more debugging and share with me more details?

**Comment by ashishkpaul** [comment] 2022-08-05 12:24
Sir in a `yarn dev` mode browser console error as

![Screenshot_2022-08-05_17-48-58](https://user-images.githubusercontent.com/16308863/183076255-656cc864-e8e4-430b-9d07-c68d6c99b203.png)

Might be it gives you some clue..

`vue.runtime.esm.js?df29:619 [Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <SfHeader> at node_modules/@storefront-ui/vue/src/components/organisms/SfHeader/SfHeader.vue
       <AppHeader> at _theme/components/AppHeader.vue
         <Anonymous>
           <LazyHydrate>
             <DefaultLayout> at _theme/layouts/default.vue
               <Root>
warn @ vue.runtime.esm.js?df29:619
flushSchedulerQueue @ vue.runtime.esm.js?df29:4331
eval @ vue.runtime.esm.js?df29:1989
flushCallbacks @ vue.runtime.esm.js?df29:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js?df29:1942
nextTick @ vue.runtime.esm.js?df29:1999
queueWatcher @ vue.runtime.esm.js?df29:4418
update @ vue.runtime.esm.js?df29:4560
notify @ vue.runtime.esm.js?df29:730
reactiveSetter @ vue.runtime.esm.js?df29:1055
proxySetter @ vue.runtime.esm.js?df29:4644
finish @ nuxt-loading.vue?45c0:76
_callee6$ @ client.js?06a0:487
tryCatch @ runtime.js?b76f:63
invoke @ runtime.js?b76f:294
eval @ runtime.js?b76f:119
asyncGeneratorStep @ asyncToGenerator.js?9e23:3
_next @ asyncToGenerator.js?9e23:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?9e23:13
_next @ asyncToGenerator.js?9e23:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?9e23:13
_next @ asyncToGenerator.js?9e23:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?9e23:13
_next @ asyncToGenerator.js?9e23:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?9e23:13
_next @ asyncToGenerator.js?9e23:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?9e23:13
_next @ asyncToGenerator.js?9e23:25
eval @ asyncToGenerator.js?9e23:32
eval @ asyncToGenerator.js?9e23:21
_render @ client.js?06a0:266
render @ client.js?06a0:266
iterator @ vue-router.esm.js?c7ab:2362
step @ vue-router.esm.js?c7ab:2004
eval @ vue-router.esm.js?c7ab:2005
eval @ vue-router.esm.js?c7ab:2384
_callee4$ @ client.js?06a0:189
tryCatch @ runtime.js?b76f:63
invoke @ runtime.js?b76f:294
eval @ runtime.js?b76f:119
asyncGeneratorStep @ asyncToGenerator.js?9e23:3
_next @ asyncToGenerator.js?9e23:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?9e23:13
_next @ asyncToGenerator.js?9e23:25
eval @ asyncToGenerator.js?9e23:32
eval @ asyncToGenerator.js?9e23:21
_loadAsyncComponents @ client.js?06a0:152
loadAsyncComponents @ client.js?06a0:152
iterator @ vue-router.esm.js?c7ab:2362
step @ vue-router.esm.js?c7ab:2004
step @ vue-router.esm.js?c7ab:2008
runQueue @ vue-router.esm.js?c7ab:2012
confirmTransition @ vue-router.esm.js?c7ab:2392
transitionTo @ vue-router.esm.js?c7ab:2260
push @ vue-router.esm.js?c7ab:2606
push @ vue-router.esm.js?c7ab:3037
push @ router.js?5783:163
_callee$ @ AppHeader.vue?f5d0:186
tryCatch @ runtime.js?b76f:63
invoke @ runtime.js?b76f:294
eval @ runtime.js?b76f:119
asyncGeneratorStep @ asyncToGenerator.js?9e23:3
_next @ asyncToGenerator.js?9e23:25
eval @ asyncToGenerator.js?9e23:32
eval @ asyncToGenerator.js?9e23:21
handleAccountClick @ AppHeader.vue?f5d0:186
invokeWithErrorHandling @ vue.runtime.esm.js?df29:1863
invoker @ vue.runtime.esm.js?df29:2188
original._wrapper @ vue.runtime.esm.js?df29:6961
/_loading/sse:1          Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR
/_loading/sse:1          GET https://vsf.dingpack.com/_loading/sse net::ERR_HTTP2_PROTOCOL_ERROR 200`

**Comment by Baroshem** [comment] 2022-08-08 08:45
Hey,

I managed to reproduce the error localy. Can you remove the 

```html
        <SfContentPage title="Loyalty card">
          <LoyaltyCard />
        </SfContentPage>
```

from MyAccount page in your project. It solved the issue in my case.

**Comment by ashishkpaul** [comment] 2022-08-08 11:06
Sir, I grep and didn't find this code anywhere. Can you specify the path
and file name

**Comment by Baroshem** [comment] 2022-08-09 09:27
MyAccount.vue  page file. 

Have you generated the project by using vue storefront cli or have you cloned this repository?

**Comment by ashishkpaul** [comment] 2022-08-09 09:29
By cloning the repo

**Comment by Baroshem** [comment] 2022-08-09 09:35
You should be using the vue storefront cli or the template-vendure instead as explained in the documentation here -> https://docs.vuestorefront.io/vendure/guide/getting-started.html#how-to-start-if-you-want-to-try-out-the-integration

**Comment by ashishkpaul** [comment] 2022-08-09 09:40
Sir I tried a lot through cli command but every time it's giving error "vsf
command not found " I will try again and inform you soon

**Comment by ashishkpaul** [comment] 2022-08-10 06:06
Yes sir, I tried on localhost as guided in the link given by you. account page not stucking through cli command installation (node 14, os: PRETTY_NAME="MX 19.4 patito feo") , thanks
console error by running `npm run dev`

No issues found.                                                                                                             11:07:05
ℹ Waiting for file changes                                                                                                   11:07:06
ℹ Memory usage: 479 MB (RSS: 1.01 GB)                                                                                        11:07:06
ℹ Listening on: http://localhost:3001/                                                                                       11:07:06

 ERROR  [Vue warn]: Invalid handler for event "click": got undefined                                                         11:07:31

found in

---> <SfBottomNavigationItem> at node_modules/@storefront-ui/vue/src/components/organisms/SfBottomNavigation/_internal/SfBottomNavigationItem.vue
       <SfBottomNavigation> at node_modules/@storefront-ui/vue/src/components/organisms/SfBottomNavigation/SfBottomNavigation.vue
         <BottomNavigation> at components/BottomNavigation.vue
           <Anonymous>
             <LazyHydrate>
               <DefaultLayout> at layouts/default.vue
                 <Root>


Mocked: useReview.searchReviews

**Comment by ashishkpaul** [comment] 2022-08-10 06:54
Hello sir, through template-vendure myaccount page is stucking or visible by refreshing the page. product variant images are also visible after refreshing the page
[https://youtu.be/ZLIOVTO1_UQ](url)
I download the repo from given link https://docs.vuestorefront.io/vendure/guide/configuration.html#setting-up-vendure-server

**Comment by ashishkpaul** [comment] 2022-08-10 12:15
through cli installation: crash on mobile, home, menu are not clickable
[https://youtu.be/MHO1Gy5nw2g](url)

**Comment by Baroshem** [comment] 2022-09-30 11:41
Closing as cannot reproduce any of these issues.

**Closed as completed by Baroshem** 2022-09-30 11:41 UTC
Labels: bug

**Comment by ashishkpaul** [comment] 2022-10-11 08:15
Let me check sir

**Comment by ashishkpaul** [comment] 2022-11-03 08:36
This error still persist Please read: https://github.com/vuestorefront-community/vendure/pull/185#issuecomment-1301762309
