### ISSUE TITLE
There is no active Order associated with the current session

### ISSUE THREAD

**Issue by Garnett1314** [vuestorefront-community/vendure#217] opened 2022-05-19 06:18 UTC
### What is your question / Please describe your issue

I follow README to deploy and when I finish registering users and do login, the login status will not be maintained. I get the following error when I click continue to ship after filling in the customer information：
{"data":{"setCustomerForOrder":{"errorCode":"NO_ACTIVE_ORDER_ERROR","message":"There is no active Order associated with the current session","__typename":"NoActiveOrderError"}}}

### What version of vendure are you using?

1.5.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment] 2022-05-19 08:36
Hey @Garnett1314 

Thanks for reporting that issue. Are you working on this repository or have you generated the project using VSF CLI?

Also, @michaelbromley could you share some light on what the issue might be from Vendure side? :)

**Comment by Garnett1314** [comment] 2022-05-19 08:48
Thank you for your reply, I cloned the project and then ran it, referencing the document https://docs.vuestorefront.io/vendure/guide/configuration.html#steps

**Comment by Baroshem** [comment] 2022-05-19 09:23
These are the instructions for development configuration. The configuration of this project repository, not the final template that the user should get. If you want to build a project based on Vendure please refer to this https://docs.vuestorefront.io/vendure/guide/getting-started.html#how-to-start-if-you-want-to-try-out-the-integration

**Comment by Garnett1314** [comment] 2022-05-19 09:46
I used VSF CLI to build the project, but the error is the same.

**Comment by Garnett1314** [comment] 2022-05-19 09:46
I used VSF CLI to build the project, but the error is the same.

**Comment by Garnett1314** [comment] 2022-05-20 03:32
Hi, the situation is that I can only add one item and the shopping cart is cleared when I refresh the page, and the login status is also cleared.I have set requireVerification: false in  VendureConfig.

**Comment by Baroshem** [comment] 2022-05-20 06:16
It looks a bit like the cookies were being reset each page refresh. Would you be able to create a reproduction repository? I will take a look at this issue

**Comment by michaelbromley** [comment] 2022-05-20 07:36
Yes that certainly sounds like the sessions are not being correctly communicated back to the Vendure server.

**Comment by Garnett1314** [comment] 2022-05-21 03:06
I've copied my local code here：https://github.com/Garnett1314/vuestorefront-new.git

**Comment by Baroshem** [comment] 2022-05-21 07:05
From what I see, this is a regular project (with the latest version). I tried it on my environment and it works just fine. I am using Node 14, Vendure 1.2.3, MacOS.

Have you included these in your vendure config?

```ts
// vendure-config.ts
...
  authOptions: {
    tokenMethod: 'bearer', // authorization header method
    requireVerification: false, // disable register by email verification
  },
```

Also, maybe you could send a video of how the issue appears? I would like to help but I basically cannot reproduce it on my environment so not sure if this is an issue with the project or environment.

**Comment by Garnett1314** [comment] 2022-05-21 07:55
Are you saying that you are using the code I copied with no problem? My environment.
node v16.15.0
Vendure 1.5.2 ,
ubuntu 20.04
I will try again using the same environment as you.

**Comment by Garnett1314** [comment] 2022-05-23 05:58
So sad, still the same problem, I'm going to collapse.

**Comment by Garnett1314** [comment] 2022-05-23 08:00
Can you tell me which module the keep login is working in?

**Comment by Baroshem** [comment] 2022-05-24 15:32
Can you check in your browser the cookies that are being generated after adding product to cart?

It seems like the issue is related to these kind of cookies and they should be generated right after login. Maybe they are not generated for some reason and that is why you cannot add it

**Comment by Garnett1314** [comment] 2022-06-16 08:13
Login return body.
{"data":{"login":{"id": "2", "identifier": "xxxxxxxxxx@mail.dsp.tw","__typename": "CurrentUser"}}}
But there is no change in the cookies,
![image](https://user-images.githubusercontent.com/31092354/174024692-dc1c1d17-a2d2-47b1-af3a-d86888d6eb63.png)

**Comment by michaelbromley** [comment] 2022-06-17 14:28
This integration is specifically designed to work with bearer tokens, not cookies - hence the need to set your Vendure config as Jakub mentioned [in the comment above](https://github.com/vuestorefront-community/vendure/issues/217#issuecomment-1133551720).

Can you confirm that you set those 2 settings in your vendure config to match the code in that comment?

**Comment by Baroshem** [comment] 2022-08-05 08:19
Closing as there was no further contact regarding the issue.

**Closed by Baroshem** 2022-08-05 08:19 UTC
