### ISSUE TITLE
[Bug]: Password Can't Be Updated From My Account

### ISSUE THREAD

**Issue by skilltimate** [vuestorefront-community/vendure#222] opened 2022-06-07 12:57 UTC
### Actual Behavior

I tried to update password from My Account section, it simply does not work.

### What version of vendure integration are you using?

Latest

### What version of Node.js are you using?

Latest

### What browser (and version) are you using?

Firefox

### What operating system (and version) are you using?

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Baroshem** [comment] 2022-06-07 14:51
Hey, could you provide more details? What are the reproduction steps, what error do you see?

**Comment by Baroshem** [comment] 2022-08-05 08:14
Closing as there is no further contact and was not able to reproduce the error.

**Closed as completed by Baroshem** 2022-08-05 08:14 UTC
Labels: bug
